# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedulaPer', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('apellidoPer', models.CharField(max_length=20)),
                ('nombrePer', models.CharField(max_length=20)),
            ],
        ),
    ]
